"""empty message

Revision ID: b35400d753d1
Revises: 
Create Date: 2022-01-05 15:32:51.797770

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b35400d753d1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "administrators",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "administrator", name="roletype"), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "users",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "administrator", name="roletype"), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "cars",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=32), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=False),
        sa.Column("interior_color", sa.String(length=32), nullable=False),
        sa.Column("tampo", sa.String(length=32), nullable=False),
        sa.Column("photo_url", sa.String(length=255), nullable=False),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_pk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_pk"],
            ["users.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cars")
    op.drop_table("users")
    op.drop_table("administrators")
    # ### end Alembic commands ###
